PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Phone TEXT,
    Role TEXT NOT NULL CHECK (Role IN ('USER', 'MANAGER', 'ADMIN')),
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court (
    CourtID INTEGER PRIMARY KEY AUTOINCREMENT,
    ManagerID INTEGER NOT NULL REFERENCES Users(UserID),
    CourtName TEXT NOT NULL,
    Location TEXT NOT NULL,
    Description TEXT,
    PricePerHour NUMERIC NOT NULL CHECK (PricePerHour >= 0),
    OpenTime TEXT NOT NULL,
    CloseTime TEXT NOT NULL CHECK (CloseTime > OpenTime),
    Status TEXT NOT NULL CHECK (Status IN ('ACTIVE', 'DISABLED', 'MAINTENANCE')),
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court_Image (
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourtID INTEGER NOT NULL REFERENCES Court(CourtID) ON DELETE CASCADE,
    Url TEXT NOT NULL,
    SortOrder INTEGER NOT NULL DEFAULT 0,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);