PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    Role VARCHAR(20) NOT NULL CHECK (Role IN ('USER', 'MANAGER', 'ADMIN')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court (
    CourtID INTEGER PRIMARY KEY AUTOINCREMENT,
    ManagerID INTEGER NOT NULL REFERENCES Users(UserID),
    CourtName VARCHAR(100) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Description TEXT,
    PricePerHour NUMERIC NOT NULL CHECK (PricePerHour >= 0),
    OpenTime TIME NOT NULL,
    CloseTime TIME NOT NULL CHECK (CloseTime > OpenTime),
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('ACTIVE', 'DISABLED', 'MAINTENANCE')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court_Image (
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourtID INTEGER NOT NULL REFERENCES Court(CourtID) ON DELETE CASCADE,
    Url VARCHAR(500) NOT NULL,
    SortOrder INTEGER NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court_Block (
    BlockID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourtID INTEGER NOT NULL REFERENCES Court(CourtID) ON DELETE CASCADE,
    BlockDate DATE NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL CHECK (EndTime > StartTime),
    Reason VARCHAR(255),
    CreatedBy INTEGER NOT NULL REFERENCES Users(UserID),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Booking (
    BookingID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID),
    CourtID INTEGER NOT NULL REFERENCES Court(CourtID),
    BookingDate DATE NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL CHECK (EndTime > StartTime),
    TotalAmount NUMERIC NOT NULL CHECK (TotalAmount >= 0),
    DepositAmount NUMERIC NOT NULL CHECK (DepositAmount >= 0),
    Status VARCHAR(20) NOT NULL CHECK (
        Status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'EXPIRED')
    ),
    HoldExpiresAt DATETIME,
    ReminderOffsetMinutes INTEGER NOT NULL DEFAULT 240 CHECK (ReminderOffsetMinutes > 0),
    CancelledAt DATETIME,
    CancelledBy INTEGER REFERENCES Users(UserID),
    CancelReason VARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankAccount (
    BankAccountID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID),
    BankName VARCHAR(100) NOT NULL,
    AccountNumber VARCHAR(50) NOT NULL,
    AccountHolderName VARCHAR(150) NOT NULL,
    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    VerifiedAt DATETIME,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (UserID, BankName, AccountNumber)
);

CREATE TABLE IF NOT EXISTS BankAccountVerification (
    VerificationID INTEGER PRIMARY KEY AUTOINCREMENT,
    BankAccountID INTEGER NOT NULL REFERENCES BankAccount(BankAccountID),
    OTPHash VARCHAR(255) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    AttemptCount INTEGER NOT NULL DEFAULT 0 CHECK (AttemptCount >= 0),
    VerifiedAt DATETIME,
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Payment (
    PaymentID INTEGER PRIMARY KEY AUTOINCREMENT,
    BookingID INTEGER NOT NULL UNIQUE REFERENCES Booking(BookingID),
    BankAccountID INTEGER NOT NULL REFERENCES BankAccount(BankAccountID),
    Amount NUMERIC NOT NULL CHECK (Amount >= 0),
    PaymentMethod VARCHAR(30) NOT NULL,
    TransactionCode VARCHAR(100) UNIQUE,
    Status VARCHAR(20) NOT NULL CHECK (
        Status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')
    ),
    RefundAmount NUMERIC CHECK (RefundAmount >= 0),
    PaidAt DATETIME,
    RefundedAt DATETIME
);

CREATE TABLE IF NOT EXISTS Notification (
    NotificationID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID),
    BookingID INTEGER REFERENCES Booking(BookingID),
    Title VARCHAR(150) NOT NULL,
    Message TEXT NOT NULL,
    Type VARCHAR(30) NOT NULL,
    IsRead BOOLEAN NOT NULL DEFAULT FALSE,
    ScheduledAt DATETIME,
    SentAt DATETIME,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CheckIn (
    CheckInID INTEGER PRIMARY KEY AUTOINCREMENT,
    BookingID INTEGER NOT NULL UNIQUE REFERENCES Booking(BookingID),
    CheckedInAt DATETIME NOT NULL,
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('CHECKED_IN')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court_Report (
    ReportID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID),
    CourtID INTEGER NOT NULL REFERENCES Court(CourtID),
    Reason VARCHAR(150) NOT NULL,
    Description TEXT,
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    ManagerResponse TEXT,
    HandledBy INTEGER REFERENCES Users(UserID),
    HandledAt DATETIME,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Court_Request (
    RequestID INTEGER PRIMARY KEY AUTOINCREMENT,
    ManagerID INTEGER NOT NULL REFERENCES Users(UserID),
    RequestType VARCHAR(20) NOT NULL CHECK (RequestType IN ('CREATE', 'UPDATE', 'DISABLE')),
    CourtID INTEGER REFERENCES Court(CourtID),
    CourtName VARCHAR(100),
    Location VARCHAR(255),
    Description TEXT,
    PricePerHour NUMERIC CHECK (PricePerHour >= 0),
    OpenTime TIME,
    CloseTime TIME CHECK (CloseTime > OpenTime),
    Reason TEXT,
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('PENDING', 'APPROVED', 'REJECTED')),
    RejectReason TEXT,
    ReviewedBy INTEGER REFERENCES Users(UserID),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ReviewedAt DATETIME
);

CREATE TABLE IF NOT EXISTS Court_Request_Image (
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    RequestID INTEGER NOT NULL REFERENCES Court_Request(RequestID) ON DELETE CASCADE,
    Url VARCHAR(500) NOT NULL,
    SortOrder INTEGER NOT NULL DEFAULT 0
);